export const APP_ID = 'CBC39C77-D7A9-4740-A56C-D8B9528A4288';
export const API_TOKEN = 'e87f2e9529e9dcd9017e6f40abeaf27bde1092d0';

export const channelCustomTypes = {
  fakeClosedTicket: 'fakeClosedTicket',
  notifications: 'notifications',
  banner: 'banner',
  promotions: 'promotions',
  salesConcierge: 'salesConcierge',
  friends: 'friends',
  support: 'support',
  announcements: 'announcements',
  delivery: 'delivery',
  flight: 'flight',
  airport: 'airport',
  blocked: 'blocked',
  bookings: 'bookings',
  nikedotcom: 'nikedotcom',
  mindset: 'mindset',
  liveEvents: 'liveEvents',
  coach: 'coach',
  carouselDemo: 'carouselDemo',
  seller: 'seller',
  fooddelivery: 'fooddelivery',
  paydemo: 'paydemo',
  audioTest: 'audioTest',
} as const;

export const translationTargetLanguages = ['es', 'ko', 'en', 'zh', 'id', 'hi', 'te', 'ta'];

export const messageCustomTypes = {
  notification: 'notification',
  banner: 'banner',
  marketing: 'marketing',
  splitPayment: 'splitPayment',
  support: 'support',
  vote: 'vote',
  splitCost: 'splitCost',
  csat: 'csat',
  csat5: 'csat5',
  interactiveResponse: 'interactiveResponse',
  orderConfirmation: 'orderConfirmation',
  map: 'map',
  splitPaymentUpdate: 'splitPaymentUpdate',
  couldNotRecognize: 'couldNotRecognize',
  adminMessageBox: 'adminMessageBox',
  adminMessageBubble: 'adminMessageBubble',
  callStarted: 'callStarted',
  callEnded: 'callEnded',
  bookingsBotStart: 'bookingsBotStart',
  typingIndicator: 'typingIndicator',
  moneyTransfer: 'moneyTransfer',
  collectMoneyRequest: 'collectMoneyRequest',
  collectMoneySent: 'collectMoneySent',
  audio: 'audio',
} as const;
